4:
  1 : ['kyros', 'philotheos', 'konstantinos', 'ieremias', 'aparhasios']
  2 : ['dios', 'amais', 'kollouthos', 'menas', 'hermauos']
  3 : ['dioscorus', 'victor', 'theodosios', 'daueit', 'pilatos'] 
  4 : ['andreas', 'isak', 'psates', 'anouphis', 'abraamios']

5:    
  1 : ['amais', 'konstantinos', 'psates', 'dios']
  2 : ['philotheos', 'isak', 'victor', 'kollouthos']
  3 : ['aparhasios', 'menas', 'daueit', 'abraamios']
  4 : ['ieremias', 'andreas', 'kyros', 'theodosios']
  5 : ['dioscorus', 'pilatos', 'anouphis', 'hermauos']
